#!/usr/bin/env python3

# Copyright (c) 2019 Brian Clemens, https://tiuxo.com

import os
import re
import subprocess

quteurl = os.environ['QUTE_URL']
qutetitle = os.environ['QUTE_TITLE']

FIFO = open(os.environ['QUTE_FIFO'], 'w')


def command(command):
    FIFO.write(command + "\n")


def add():
    soundcloudplaylist = re.search('soundcloud.com/.*/sets/.*', quteurl)

    if soundcloudplaylist:
        url = 'soundcloud://url/' + soundcloudplaylist.group()
        subprocess.call(['mpc', 'load', url])
        command('message-info "URL added to MPD"')
    else:
        command('message-warning "URL does not match any MPD plugins"')


add()

FIFO.close()
