#!/bin/sh

# Aliases for git

# Git commit with message
alias gc='git commit -am'

# Git log with graph
alias gl='git log --graph --oneline --decorate --all'

# Simple git status
alias gs='git status -sb'

# Show blobs in a git repository
git_blobs() {
    git rev-list --objects --all \
    | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
    | awk '/^blob/ {print substr($0,6)}' \
    | sort --numeric-sort --key=2 \
    | cut --complement --characters=13-40 \
    | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
}

git_purge() {
    git filter-branch -f --index-filter 'git rm -r --cached --ignore-unmatch "$@"' HEAD
}
