#!/bin/sh

# Aliases for Ansible (https://www.ansible.com)

# Go to Ansible home directory
alias ad='cd $ANSIBLE_HOME'

# Use vault password script
# Not in ansible.cfg so as not to interfere with AWX
export vid="prod@scripts/vault_password_prod.sh"
# 
# alias ansible='ansible --vault-id="$vid"'
# alias ansible-playbook='ansible-playbook --vault-id="$vid"'
# alias ansible-vault='ansible-vault --vault-id="$vid"'
