#!/bin/zsh

# Autosuggestions by https://github.com/zsh-users/zsh-autosuggestions

zplugin ice wait"0" atload"_zsh_autosuggest_start" lucid
zplugin light zsh-users/zsh-autosuggestions

# Disable for large buffers
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

# Use dark gray
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=241"

# Contextual suggestions
ZSH_AUTOSUGGEST_STRATEGY="match_prev_cmd"

# Asynchronous
ZSH_AUTOSUGGEST_USE_ASYNC=1
